### ISSUE TITLE
Error -104

### ISSUE THREAD

**Issue by stepmen** [macherel/Connect-IQ-QR-Code-Viewer#6]
Hello, I try to add a CARDVIEW data but i get -104 error

**Comment by macherel** [comment]
I'm really sorry I did not answer sooner.

-104 error means that bluetooth connection is not available.
Please connect your watch to your phone or use offline mode in the last version of the widget (Note that data connection is still needed the first time the widget is loaded or when qr code are changed)

**Comment by IGx89** [comment]
How do we activate offline mode? I've updated to the latest version (I can tell since the label moved from below to the top, slightly cut off now) but every time I scroll to the widget with BT disabled it gives that -104 error. If I have BT enabled it works, but then trying it again with BT disabled doesn't. I just have a single QR code entered. I'm using a Fenix 5+.

**Comment by macherel** [comment]
You can activate offline mode in the widget settings (next to last setting)

-104 error appear each time the widget try to load an image without bluetooth

For any other problem or help needed, please open a new ticket.
